[features]
seeds = false
skip-lint = false
[programs.devnet]
mytestproject = "265EvWY8CCMfDxHnAVDGvThRZ8dGghVtcQ2Qgj8NzaAu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/joeylaya/.config/solana/id.json"

[scripts]
test = "node tests/mytestproject.js"
